baseurl = "https://favas.dev/"
languageCode = "en-us"
theme = "terminal"

[pagination]
pagerSize = 10

[markup.goldmark.renderer]
unsafe = true

[params]
# dir name of your main content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "blogs"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 5

showLanguageSelector = false
fullWidthTheme = false
centerTheme = true

# if your resource directory contains an image called `cover.(jpg|png|webp)`,
# then the file will be used as a cover automatically.
# With this option you don't have to put the `cover` param in a front-matter.
autoCover = true

# set post to show the last updated
# If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
showLastUpdated = false

# Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
# updatedDatePrefix = "Updated"

# whether to show a page's estimated reading time
readingTime = false

# whether to show a table of contents
# can be overridden in a page's front-matter
Toc = false

# set title for the table of contents
# can be overridden in a page's front-matter
# TocTitle = "Table of Contents" # default


[params.twitter]
# set Twitter handles for Twitter cards
# see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
# do not include @
creator = ""
site = ""

[languages]
[languages.en]
languageName = "English"
title = "Favas M"

[languages.en.params]
subtitle = "Favas M - 23-year-old backend engineer specializing in Golang and Python for web development. Passionate about cybersecurity and low-level engineering. Co-founder of initcrew, a cybersecurity community in Kerala."
owner = "Favas M"
keywords = "clevrf0x, Favas M, Backend Engineer, Golang, Python, web development, cybersecurity, low-level engineering, Zig, Rust, C, C++, Hack The Box, CTF, initcrew, hacking, developer, Kerala, Go developer, Python developer, software engineer, reverse engineering"
copyright = "clevrf0x"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found"
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[languages.en.params.logo]
logoText = "clevrf0x"
logoHomeLink = "/"

[languages.en.menu]
# [[languages.en.menu.main]]
# identifier = "home"
# name = "Home"
# url = "/"
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "blogs"
name = "Blogs"
url = "/blogs"
[[languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
